#!/bin/sh

separator="$(~/.config/i3blocks/blocks/util/separator)"

# menu icon
echo -e "<span>$separator </span>"
#  ☰  

# mouse buttons
case $BLOCK_BUTTON in
    1) i3-dmenu-desktop --dmenu="/usr/bin/rofi -dmenu -i -p 'apps:' -width 25 -padding 19 -yoffset -180 -xoffset 500" ;; #left click rofi
    2) rofi-logout ;; #middle click, logout menu
    3) rofi-s  #right click, rofi web search 
esac 
