#!/bin/bash

separator=$($BLOCKS_DIR/separator)

get_unread()
{
  # find ~/mail -type f | grep -vE ',[^,]*S[^,]*$' | wc -l
  notmuch count tag:unread
}

re='^[0-9]+$'
msgs=$(get_unread)
if ! [[ $msgs =~ $re  ]] || [[ $msgs -eq 0 ]] ; then
  echo ""
else
  echo "<span>$separator $msgs</span>"
fi

# mouse buttons
case $BLOCK_BUTTON in
    1) termite --exec mutt --title mutt_termite
esac 
