#!/bin/sh

separator="$(~/.config/i3blocks/blocks/util/separator)"

echo -e "<span font='8.5' font_stretch='expanded' font_weight='ultralight' foreground='#cccccc' >$separator  $(date +"%a %d %b %Y $separator  %T")</span>"
#  ☰  

# mouse buttons
case $BLOCK_BUTTON in
    1) termite --exec gcal-calm --title gcal-calm_termite
esac 
