#!/bin/sh

nowplaying() {
  SONG="$(
    if ps -C cmus > /dev/null; then
      artist=$(cmus-remote -Q | grep '^tag artist' | sed '/^tag artistsort/d'  | awk '{gsub("tag artist ", "");print}' )
      title=$(cmus-remote -Q  | grep '^tag title' | awk '{gsub("tag title ", "");print}')
      echo "${artist} - ${title}";
    else
      echo
    fi
  )"
  if [ "$(echo ${SONG} | wc -m)" -ge 61 ]; then
    SONG="$(echo ${SONG} | head -c 61)..."
  fi
  echo "${SONG}"
}

playing() {
  if [ "$(cmus-remote -Q | grep 'status playing')" ]; then
    PLAYING=''
  elif [ "$(cmus-remote -Q | grep 'status paused')" ]; then
    PLAYING=''
  else
    PLAYING=''
  fi
  echo "${PLAYING}"
}

echo -e "$(playing) $(nowplaying)"
